name: Run-Drake-Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build-container:
    name: Run workflow
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build container and push to container registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          push_image_and_stages: false
          image_name: rstudio
          dockerfile: Dockerfile

      - name: Build docker image
        run: docker build . --file Dockerfile --tag rstudio

      - name: Run Drake workflow
        run: docker run -v $(pwd):/home -w /home --name rstudio_container rstudio_image Rscript main.R
