name: Run-Drake-Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build-container:
    name: Build docker container
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build docker image
        # run: docker build . --file Dockerfile --tag r-env:$(date +%s)
        run: docker-compose up --build -d
      - name: Check running images
        run: docker ps -a
