name: Run-Drake-Workflow

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chechout@v2
      - run: docker build . --file Dockerfile --tag r-env:$(date +%s)
